export const ciphersDescriptions = {
  "Alura Cipher":
    "Este método criptográfico es una forma de cifrado basada en la sustitución de letras. Es un cifrado simple que reemplaza cada una de las cinco vocales (a, e, i, o, u) por una secuencia de caracteres específica que se le es proporcionado.",
  "ROT Cipher":
    "Es un sencillo cifrado César, es decir, un método criptográfico clásico basado en el cifrado por desplazamiento. Esta técnica de cifrado incluye cuatro variantes: ROT13, ROT5, ROT18 y ROT47. ROT13 sustituye cada letra por la letra que está 13 posiciones más adelante en el alfabeto, mientras que ROT5 reemplaza cada letra por la letra que está 5 posiciones más adelante en el alfabeto numérico (0-9). ROT18 combina ROT13 y ROT5, primero cifrando el texto con ROT13 y luego cifrando el resultado con ROT5. Por otro lado, ROT47 es similar a ROT13 pero utiliza un conjunto de caracteres ASCII más amplio y reemplaza cada letra con la letra que está 47 posiciones más adelante en ese conjunto. Es importante tener en cuenta que estos algoritmos no ofrecen seguridad criptográfica real y suelen utilizarse como ejemplo de cifrado débil.",
  "Cifrado César":
    "En criptografía, el cifrado César, también conocido como cifrado por desplazamiento, código de César o desplazamiento de César, es una de las técnicas de codificación más simples y más usadas. Es un tipo de cifrado por sustitución en el que una letra en el texto original es reemplazada por otra letra que se encuentra un número fijo de posiciones más adelante en el alfabeto. Este método debe su nombre, según Suetonio, a Julio César, que lo usaba para comunicarse con sus generales.",
  "Bacon Cipher":
    "El cifrado de Bacon es un híbrido entre los sistemas criptográficos y los esteganográficos compartiendo características de ambos. Cada letra del alfabeto es reemplazada por una secuencia de cinco bits, dos de los cuales son 0 y tres de los cuales son 1. Estos bits se pueden representar por medio de dos símbolos diferentes (por ejemplo, A y B). En otras palabras, utiliza secuencias de dos caracteres para representar cada letra del alfabeto original. Cada letra se reemplaza por una secuencia de cinco caracteres 'A' y 'B', en donde la posición de 'A' y 'B' indica la letra original.",
  "Vigenère Cipher":
    "El cifrado de Vigenère es un método de cifrado de sustitución polialfabético, que consiste en utilizar una tabla de sustitución (conocida como 'tabla de Vigenère') para cifrar mensajes. La tabla de Vigenère se construye a partir de una clave que se utiliza para desplazar cada letra del mensaje original hacia la derecha en un número determinado de posiciones en el alfabeto. El número de posiciones que se desplazan las letras depende de la posición de la letra dentro de la clave, y esto hace que cada letra del mensaje original se sustituya por una letra diferente. De esta manera, el mensaje cifrado se vuelve mucho más difícil de descifrar sin conocer la clave utilizada.",
};
